notifications:
  email: false

matrix:
  include:
    - sudo: required
      language: generic
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - sudo: required
      language: generic
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32
    - os: osx
      language: generic

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull $DOCKER_IMAGE; fi

script:
  - travis/build-wheels-${TRAVIS_OS_NAME}.sh
  - ls wheelhouse
