schedules:
  commit_849:
    schedule: per_commit
    branches:
      include: [master]
    env_vars: |
      EVENT_LOOP_MANAGER='libev'
  weekly_async2:
    schedule: weekly
    branches:
      include: [master]
    env_vars: |
      EVENT_LOOP_MANAGER='async'
  weekly_twister2:
    schedule: weekly
    branches:
      include: [master]
    env_vars: |
      EVENT_LOOP_MANAGER='twisted'
os:
  - ubuntu/trusty64/python-docker
build:
  - script: |
      echo "Running Python wheel builder job"
